package com.example.employeemanagement.Employee;


import java.time.LocalDate;
import java.util.List;

import org.springframework.boot.CommandLineRunner;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

@Configuration
public class EmployeeConfig {

    @Bean
    CommandLineRunner commandLineRunner(EmployeeRepository repository) {
        return args -> {
            // id will be generated by jpa so ..using the constructor without id
            Employee aaaa = new Employee("aaaa","gupta","aaaa@gmail.com");
            Employee bbbb = new Employee("bbbb","kaurav", "bbbb@gmail.com");
            Employee cccc = new Employee("cccc","khare", "cccc@gmail.com");
            Employee eeee = new Employee("eeee","ojha","eeee@gmail.com");
            Employee ffff = new Employee("ffff","jadon","bbbb@gmail.com");
            

            repository.saveAll(
                 List.of(aaaa,bbbb,eeee,ffff,cccc)
            );
            System.out.println("Employees saved in database");
        };
    }



}

